In [ ]:

aList = ["Nicky", 20, "Toronto", True]
print(aList)



['Nicky', 20, 'Toronto', True]


In [ ]:

aList = ["John", 33, "Toronto", True]
print(aList)

['John', 33, 'Toronto', True]


In [ ]:
from datetime import date
tgl_v1 = date.today()
print(tgl_v1)

import datetime as vDate
hari = vDate.date.day
print(hari)

tanggal = vDate.date.today()
print(tanggal)

mahasiswa = ["Nicky Brilliant Suryadi Langit", "2024071027", "Informatika", "DAA",
             f"{tanggal.day}-{tanggal.month}-{tanggal.year}",
             "Universitas Pembangunan Jaya"]
print(mahasiswa)

print("NIM", mahasiswa[1])
print("Kampus", mahasiswa[5])


2025-09-15
<attribute 'day' of 'datetime.date' objects>
2025-09-15
['Nicky Brilliant Suryadi Langit', '2024071027', 'Informatika', 'DAA', '15-9-2025', 'Universitas Pembangunan Jaya']
NIM 2024071027
Kampus Universitas Pembangunan Jaya


In [ ]:
print("Nama =", mahasiswa[0])
print("NIM =", mahasiswa[1])
print("Prodi =", mahasiswa[2])
print("kampus =", mahasiswa[5])
print("MK =", mahasiswa[3])
print("datetime =", mahasiswa[4])

Nama = Nicky Brilliant Suryadi Langit
NIM = 2024071027
Prodi = Informatika
kampus = Universitas Pembangunan Jaya
MK = DAA
datetime = 15-9-2025


In [ ]:
print("Nama =", mahasiswa[0 : 1])

Nama = ['Nicky Brilliant Suryadi Langit']


# **Cetak NIM dan Prodi menggunakan slicing**

In [ ]:
print("NIM =", mahasiswa[1 : 3])

NIM = ['2024071027', 'Informatika']


In [ ]:
print("MK =", mahasiswa[3 : 5])

MK = ['DAA', '15-9-2025']


In [ ]:
upj = ["Universitas", "Pembangunan", "Jaya"]
print(upj)

['Universitas', 'Pembangunan', 'Jaya']


# **list**


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
print(bin_colors[1])

Green


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
print(bin_colors[0:2])   # ['Red', 'Green']

['Red', 'Green']


In [ ]:
bin_colors = ['Red', 'Green', 'Blue', 'Yellow']
for aColor in bin_colors:
    print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


# **tupes**

In [ ]:
bin_colors=('Red', 'Green', 'Blue', 'Yellow')
print(bin_colors[1])
print(bin_colors[2:])

Green
('Blue', 'Yellow')


# **Latihan Tambahkan Kata UPJ**

In [ ]:
for aMhs in mahasiswa:
  print(aMhs + ' UPJ ')

Nicky Brilliant Suryadi Langit UPJ 
2024071027 UPJ 
Informatika UPJ 
DAA UPJ 
15-9-2025 UPJ 
Universitas Pembangunan Jaya UPJ 


# **Latihan**

In [ ]:
nested = (100, (200, 400, 600), 300,(400,800))
print(nested)

(100, (200, 400, 600), 300, (400, 800))


# **Dictionary**

In [ ]:
bin_colors = {
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors.get('approved_color')

'Green'

In [ ]:
bin_colors['approved_colors']="purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red', 'approved_colors': 'purple'}


# Sets

In [ ]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [ ]:
green = {'grass', 'leaves', 'leaves'}
print(green)

{'leaves', 'grass'}


# **Latihan**

In [ ]:
yellow|red
{'blod', 'rose', 'danselions', 'fire hydrant', 'leaves'}
yellow&red
{'fire hydrant', 'leaves'}

{'fire hydrant', 'leaves'}

In [ ]:
yellow = {'blod', 'rose', 'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood'}

print("Union", yellow | red)

Union {'blod', 'leaves', 'blood', 'dandelions', 'rose', 'fire hydrant'}


# **DataFrame**

In [ ]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df

0       1   2      3
0  1   Fares  32   True
1  2   Elena  23  False
2  3  Steven  40   True

In [ ]:
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[['name', 'age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [ ]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [ ]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [ ]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

# **Latihan**

In [ ]:
import pandas as pd

data = {
    "No": [1, 2, 3],
    "Prodi": ["Informatika", "Sistem Informasi", "Teknik Sipil"],
    "Mahasiswa": [50, 55, 40],
    "Laki-laki": [30, 30, 30],
    "Perempuan": [20, 25, 10]
}

mhs = pd.DataFrame(data)

print(mhs)


   No             Prodi  Mahasiswa  Laki-laki  Perempuan
0   1       Informatika         50         30         20
1   2  Sistem Informasi         55         30         25
2   3      Teknik Sipil         40         30         10


# **Matrix**

In [ ]:
import numpy as np

myMatrix = np.array([[11, 12, 13],
                     [21, 22, 23],
                     [31, 32, 33]])

print(myMatrix)



[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [ ]:
print(type(myMatrix))

<class 'numpy.ndarray'>


# **Latihan Matrix**

In [ ]:
import numpy as np

myMatrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
])

print("Matrix awal:")
print(myMatrix)

transposeMatrix = myMatrix.T
print("\nMatrix setelah transpose:")
print(transposeMatrix)


Matrix awal:
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Matrix setelah transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [ ]:
print("\nTipe data:", type(myMatrix))


Tipe data: <class 'numpy.ndarray'>


# **Vector**

In [3]:
myVector = [22, 33, 44, 55]
print(myVector)


[22, 33, 44, 55]


In [4]:
print(type(myVector))

<class 'list'>


In [1]:
import numpy as np
myVector = np.array([22, 33, 44, 55])
print(myVector)

[22 33 44 55]


In [5]:
print(type(myVector))

<class 'list'>


# **Stack**

In [16]:
class Stack:
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def push(self, item):
        self.items.append(item)

    def pop(self):
        return self.items.pop()

    def peek(self):
        return self.items[len(self.items) - 1]

    def size(self):
        return len(self.items)

Populate the stack

In [13]:
stack = Stack()

# Menambahkan elemen ke stack
stack.push('Red')
stack.push('Green')
stack.push('Blue')
stack.push('Yellow')


pop

In [14]:
print(stack.pop())

Yellow


In [15]:
print(stack.isEmpty())

False


# **Queue**

In [17]:
class Queue(object):
    def __init__(self):
        self.items = []

    def isEmpty(self):
        return self.items == []

    def enqueue(self, item):
        self.items.insert(0, item)

    def dequeue(self):
        return self.items.pop()

    def size(self):
        return len(self.items)


In [23]:
queue = Queue()

queue.enqueue('Red')
queue.enqueue('Green')
queue.enqueue('Blue')
queue.enqueue('Yellow')


In [19]:
print(queue.size())

4


In [20]:
print(queue.dequeue())

Red


In [21]:
print(queue.dequeue())

Green
